# Generated by Django 5.1.3 on 2024-11-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="core.product",
            ),
        ),
    ]
