from django.urls import path, include

from .views import (
    index,
    about,
    blog_detail,
    blog,
    contact,
    home2,
    vendor,
    product_detail,
    product,
    shoping_cart,
    vendor_products,
    category_products,
    tag_list,
    reviews,
    save_review,
    search_product,
    filter_products,
    addToCart,
    shoping_list,
    update_cart,
    delete_cart,
    invoice,
    paypal_failed,
    paypal_completed,
    addToWish,
    wishListPage,
    remove_wish,
)

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("blog-detail/", blog_detail, name="blog-detail"),
    path("blog/", blog, name="blog"),
    path("contact/", contact, name="contact"),
    path("home2/", home2, name="home2"),
    path("vendor/", vendor, name="vendor"),
    path("product-detail/<int:pk>", product_detail, name="product-detail"),
    path("product/<str:cid>", product, name="product"),
    path("shopping-cart/", shoping_cart, name="shopping-cart"),
    path("vendor_products/<str:vid>", vendor_products, name="vendor-products"),
    path("category_products/<str:cid>", category_products, name="category-products"),
    path("tag/<slug:slug>", tag_list, name="tag-list"),
    path("reviews/<int:pk>", reviews, name="reviews"),
    path("new-review/<int:pk>", save_review, name="new-review"),
    path("search-product/>", search_product, name="search-product"),
    path("filter-products/", filter_products, name="filter-products"),
    path("addToCart/", addToCart, name="addToCart"),
    path("shoppingCart/", shoping_cart, name="shopping-cart"),
    path("shopping-list/", shoping_list, name="shopping-list"),
    path("update-cart/", update_cart, name="updateCart"),
    path("delete-cart/", delete_cart, name="deleteCart"),
    path("invoice/", invoice, name="invoice"),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("payment-completed/", paypal_completed, name="payment-completed"),
    path("payment-failed/", paypal_failed, name="payment-filed"),
    path("add-to-wishList/", addToWish, name="addToWish"),
    path("wishlist/", wishListPage, name="wishlist"),
    path("remove-wish/", remove_wish, name="remove-wish"),
]
